# This is a basic workflow to help you get started with Actions

name: RetryWith3AttemptsPw1

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: [parent3]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Trigger Workflow
        id: trigger_workflow
        run: |
          for ($i=1; $i -le 3; $i++) {
          
            Write-Output ${{ secrets.GITHUB_TOKEN }}
            write-Host $env:GITHUB_REPOSITORY
               $response = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/parent3.yml/dispatches" 
            -Headers @{
              "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"
              "Accept" = "application/vnd.github.v3+json"
            } 
            -Method Post 
            -Body (@{ "ref" = "main" } | ConvertTo-Json)
            
            Write-Host "Wait for 30 seconds to trigger dispatch event"
            Start-Sleep -Seconds 30
             $response = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/parent3.yml/runs" `
              -Headers @{ "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}" } `
              -Method Get
            $latest_run = $response.workflow_runs | Sort-Object -Property updated_at | Select-Object -Last 1
            $conclusion = $latest_run.conclusion
             Write-Output  $latest_run | ConvertTo-Json
            if ($conclusion -eq "success") {
              Write-Host "Workflow is successful."
              exit 0
            }
            else {
              if ($i -eq 3) {
                Write-Host "Workflow is not successful after 3 attempts. Exiting..."
                exit 1
              }
              else {
                Write-Host "Workflow is not successful. Retrying in 30 seconds..."
                Start-Sleep -Seconds 30
              }
            }
          }
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
