name: Build_Dev1
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch: {}
  workflow_call: {}
  workflow_run:
    workflows: BuildAndUnitTest
    types:
      - completed

jobs:
  on-success:
    runs-on:
  
      - ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: meta_runner_test
        run: |-
          echo  "test meta runner"
      - name: BuildStep_CommandLine
        shell: sh
        run: |-
        
          echo "in test"
  on-failure:
    runs-on:

      - ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: RetryTrigger
        shell: sh
        run: |-
          for i in {1..3}
          do
            echo "Wait for 30 seconds to trigger dispatch event"
          
          done
  Build_NUnitTests:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/Build_NUnitTests.yml
  Build_Manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/Build_Manual.yml
  Build_Dev1:
    needs:
      - Build_NUnitTests
      - Build_Manual
    runs-on:
 
      - ubuntu-latest
    steps:
      - name: meta_runner_test
        run: |-
          echo  "test meta runner"
      - name: BuildStep_CommandLine
        shell: cmd
        run: |-
          cd Test
          echo "in test"
