name: Build_Dev1
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch: {}
  workflow_call: {}
  workflow_run:
    workflows: BuildAndUnitTest
    types:
      - completed

jobs:
  on-success:
    runs-on:
  
      - ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: meta_runner_test
        run: |-
          echo  "test meta runner"
      - name: BuildStep_CommandLine
        shell: sh
        run: |-
        
          echo "in test"
  on-failure:
    runs-on:

      - ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: RetryTrigger
        shell: sh
        run: |-
          for i in {1..3}; do
          response1=$(curl -X POST \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           "https://api.github.com/repos/${{ github.repository }}/actions/workflows/BuildAndUnitTest.yml/dispatches" \
           -d '{"ref":"main"}')
           echo "Wait for: 30seconds to trigger dispatch event" \
           sleep 30s
          
           response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/BuildAndUnitTest.yml/runs")
                   # echo $response
                   
          
           echo "this test"
           workflow_runs=$(echo "$response" | jq -r '.workflow_runs')
           
           printf "%s" $workflow_runs > workflow_runs.json
           latest_run=$(cat workflow_runs.json | jq 'max_by(.updated_at)')
           
           printf "%s" $latest_run > latest_workflow_run.json
           conclusion=$(echo "$latest_run" | jq -r '.conclusion')
           echo "$conclusion"
        
          done
  Build_NUnitTests:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/Build_NUnitTests.yml
  Build_Manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/Build_Manual.yml
  Build_Dev1:
    needs:
      - Build_NUnitTests
      - Build_Manual
    runs-on:
 
      - ubuntu-latest
    steps:
      - name: meta_runner_test
        run: |-
          echo  "test meta runner"
      - name: BuildStep_CommandLine
        shell: cmd
        run: |-
          cd Test
          echo "in test"
