# This is a basic workflow to help you get started with Actions

name: RetryWith3Attempts

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: [parent1]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - name: Trigger Workflow
        id: trigger_workflow
        run: |
         for i in {1..3}; do
          response1=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/parent1.yml/dispatches" \
            -d '{"ref": "main"}')
          echo $response1
         
          echo "Wait for 30 seconds to trigger dispatch event"

          sleep 30s
      
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/parent1.yml/runs")
                   # echo $response
                    workflow_runs=$(echo "$response" | jq -r '.workflow_runs')
                    echo "This is workflow run"
                    # echo $workflow_runs
            printf "%s" $workflow_runs > workflow_runs.json
      
          latest_run=$(cat workflow_runs.json | jq 'max_by(.updated_at)')
          # echo $latest_run
           printf "%s" $latest_run > latest_workflow_run.json

      
            cat latest_workflow_run.json 
         
      
            conclusion=$(echo "$latest_run" | jq -r '.conclusion')
           
            if [[ "$conclusion" == "success" ]]; then
              echo "Workflow is successful."
              break
            elif [[ "$i" == 3 ]]; then
              echo "Workflow is not successful after 3 attempts. Exiting..."
              exit 1
            else
              echo "Workflow is not successful. Retrying in 30 seconds..."
             
            fi
          done
