# This is a basic workflow to help you get started with Actions

name: RetryWith3AttemptsPw

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: [parent1]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Trigger Workflow
        id: trigger_workflow
        run: |
          for ($i=1; $i -le 3; $i++) {
          
            Write-Output ${{ secrets.GITHUB_TOKEN }}
            write-Host $env:GITHUB_REPOSITORY
               $response = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/parent1/dispatches" `
            -Headers @{
              "Authorization" = "Bearer +${{ secrets.GITHUB_TOKEN }}
              "Accept" = "application/vnd.github.v3+json"
            } `
            -Method Post `
            -Body (@{ "ref" = "main" } | ConvertTo-Json)
            
          }
